In [2]:
# import pandas and statistics

import pandas as pd
import statistics as st

In [3]:
# read in mapping codes
# male = 1, female = 2, pilot = 1, non-pilot = 0

mapping_codes = pd.read_csv("Mapping Codes.csv")
mapping_codes

  Category                                Value  Code
0   Gender                                 Male     1
1   Gender                               Female     2
2    Pilot                                  Yes     1
3    Pilot                                   No     0
4     Race                                White     1
5     Race            Black or African American     2
6     Race     American Indian or Alaska Native     3
7     Race                                Asian     4
8     Race  Native Hawaiian or Pacific Islander     5
9     Race                                Other     6

In [4]:
# read in pilot and non-pilot data

data = pd.read_csv("Pilot Non-Pilot SUMMARY Fairness.csv")
data

,IS_PILOT,AGE,Gender,Race,PSS,JSS,MFI,GF,PF,RA,RM,MF
0,1,21,1,5,0.464286,0.40,0.530000,0.650000,0.750000,0.650000,0.500000,0.100000
1,1,19,2,1,0.410714,0.50,0.568421,0.500000,0.933333,0.800000,0.450000,0.250000
2,1,21,1,1,0.357143,0.25,0.540000,0.550000,0.350000,0.600000,0.400000,0.800000
3,1,19,1,1,0.160714,0.00,0.500000,0.550000,0.450000,0.450000,0.500000,0.550000
4,1,18,2,1,0.392857,0.30,0.420000,0.300000,0.400000,0.600000,0.500000,0.300000
5,1,20,1,1,0.428571,0.30,0.590000,0.600000,0.700000,0.500000,0.600000,0.550000
6,1,19,2,1,0.375000,0.30,0.547368,0.533333,0.500000,0.650000,0.500000,0.550000
7,1,18,2,1,0.464286,0.50,0.550000,0.550000,0.700000,0.550000,0.550000,0.400000
8,1,20,2,1,0.321429,0.20,0.570000,0.500000,0.550000,0.550000,0.600000,0.650000
9,1,18,1,1,0.285714,0.00,0.530000,0.750000,0.650000,0.350000,0.450000,0.450000
10,1,20,1,1,0.446429,0.55,0.350000,0.250000,0.450000,0.550000,0.350000,0.150000
11,1,18,1,1,0.392857,0.15,0.460000,0.450000,0.200000,0.600000,0.550000,0.500000
12,1,19,2,1,0.482143,0.40,0.320000,0.250000,0.450000,0.200000,0.250000,0.450000
13,1,26,1,1,0.250000,0.20,0.670000,0.650000,0.700000,0.700000,0.650000,0.650000
14,1,19,1,1,0.464286,0.40,0.570000,0.550000,0.650000,0.700000,0.650000,0.300000
15,1,18,1,4,0.339286,0.30,0.588235,0.500000,0.800000,0.733333,0.533333,0.450000
16,1,28,1,1,0.625000,0.15,0.290000,0.150000,0.450000,0.200000,0.300000,0.350000
17,1,21,1,1,0.642857,0.40,0.300000,0.100000,0.200000,0.500000,0.400000,0.300000
18,1,21,2,1,0.857143,0.55,0.250000,0.050000,0.300000,0.300000,0.250000,0.350000
19,1,19,1,1,0.214286,0.20,0.613333,0.600000,1.000000,0.333333,0.400000,0.733333
20,1,20,1,1,0.464286,0.10,0.550000,0.500000,1.000000,0.733333,0.450000,0.450000
21,1,23,2,1,0.375000,0.60,0.430000,0.150000,0.350000,0.600000,0.550000,0.500000
22,1,21,1,4,0.428571,0.25,0.580000,0.500000,0.650000,0.450000,0.600000,0.700000
23,1,18,1,1,0.321429,0.20,0.770000,0.850000,0.800000,0.850000,0.600000,0.750000
24,1,18,1,1,0.214286,0.20,0.680000,0.600000,0.800000,0.700000,0.600000,0.700000
25,1,23,2,4,0.464286,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1,19,2,4,0.625000,1.00,0.500000,0.450000,0.550000,0.700000,0.400000,0.400000
27,1,20,1,1,0.339286,0.20,0.626667,0.450000,0.933333,0.733333,0.533333,0.500000
28,1,21,2,5,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1,21,1,1,0.250000,0.20,0.580000,0.550000,0.700000,0.700000,0.500000,0.450000
30,1,22,2,2,0.517857,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1,18,2,1,0.357143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,1,19,1,1,0.375000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1,21,1,4,0.446429,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,0,19,2,4,0.500000,0.00,0.490000,0.450000,0.550000,0.450000,0.500000,0.500000
35,0,20,1,1,0.696429,0.70,0.280000,0.350000,0.200000,0.100000,0.350000,0.400000
36,0,18,2,2,0.535714,0.90,0.440000,0.300000,0.550000,0.600000,0.450000,0.300000
37,0,21,2,1,0.660714,0.30,0.330000,0.150000,0.450000,0.600000,0.200000,0.250000
38,0,20,2,1,0.500000,0.05,0.610000,0.650000,0.500000,0.650000,0.700000,0.550000
39,0,20,4,6,0.571429,0.30,0.480000,0.400000,0.550000,0.450000,0.400000,0.600000
40,0,19,1,4,0.250000,0.25,0.620000,0.600000,0.800000,0.650000,0.350000,0.700000
41,0,18,2,4,0.607143,0.40,0.410000,0.250000,0.350000,0.500000,0.600000,0.350000
42,0,20,2,6,0.642857,0.95,0.460000,0.450000,0.600000,0.450000,0.450000,0.350000
43,0,21,2,1,0.392857,0.00,0.660000,0.700000,0.700000,0.600000,0.600000,0.700000
44,0,18,2,4,0.642857,0.55,0.330000,0.250000,0.350000,0.450000,0.350000,0.250000
45,0,18,2,1,0.392857,0.65,0.460000,0.350000,0.700000,0.700000,0.400000,0.150000
46,0,18,2,4,0.625000,0.60,0.300000,0.200000,0.200000,0.200000,0.450000,0.450000
47,0,20,1,1,0.357143,0.50,0.510000,0.350000,0.550000,0.700000,0.500000,0.450000
48,0,18,1,4,0.714286,0.80,0.473684,0.400000,0.533333,0.350000,0.550000,0.550000
49,0,19,2,2,0.750000,0.95,0.380000,0.400000,0.300000,0.600000,0.400000,0.200000
50,0,19,2,4,0.446429,0.50,0.320000,0.300000,0.300000,0.400000,0.300000,0.300000
51,0,20,2,2,0.482143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,0,19,2,4,0.410714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,0,18,2,4,0.571429,0.00,0.360000,0.250000,0.300000,0.400000,0.400000,0.450000
54,0,21,2,1,0.285714,0.20,0.680000,0.600000,0.800000,0.750000,0.650000,0.600000
55,0,19,1,4,0.625000,0.70,0.550000,0.550000,0.550000,0.600000,0.550000,0.500000
56,0,19,2,1,0.660714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,0,18,2,4,0.375000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,0,21,2,1,0.625000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,0,20,1,1,0.607143,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# drop rows with NaN values

data = data.dropna()
data

,IS_PILOT,AGE,Gender,Race,PSS,JSS,MFI,GF,PF,RA,RM,MF
0,1,21,1,5,0.464286,0.40,0.530000,0.650000,0.750000,0.650000,0.500000,0.100000
1,1,19,2,1,0.410714,0.50,0.568421,0.500000,0.933333,0.800000,0.450000,0.250000
2,1,21,1,1,0.357143,0.25,0.540000,0.550000,0.350000,0.600000,0.400000,0.800000
3,1,19,1,1,0.160714,0.00,0.500000,0.550000,0.450000,0.450000,0.500000,0.550000
4,1,18,2,1,0.392857,0.30,0.420000,0.300000,0.400000,0.600000,0.500000,0.300000
5,1,20,1,1,0.428571,0.30,0.590000,0.600000,0.700000,0.500000,0.600000,0.550000
6,1,19,2,1,0.375000,0.30,0.547368,0.533333,0.500000,0.650000,0.500000,0.550000
7,1,18,2,1,0.464286,0.50,0.550000,0.550000,0.700000,0.550000,0.550000,0.400000
8,1,20,2,1,0.321429,0.20,0.570000,0.500000,0.550000,0.550000,0.600000,0.650000
9,1,18,1,1,0.285714,0.00,0.530000,0.750000,0.650000,0.350000,0.450000,0.450000
10,1,20,1,1,0.446429,0.55,0.350000,0.250000,0.450000,0.550000,0.350000,0.150000
11,1,18,1,1,0.392857,0.15,0.460000,0.450000,0.200000,0.600000,0.550000,0.500000
12,1,19,2,1,0.482143,0.40,0.320000,0.250000,0.450000,0.200000,0.250000,0.450000
13,1,26,1,1,0.250000,0.20,0.670000,0.650000,0.700000,0.700000,0.650000,0.650000
14,1,19,1,1,0.464286,0.40,0.570000,0.550000,0.650000,0.700000,0.650000,0.300000
15,1,18,1,4,0.339286,0.30,0.588235,0.500000,0.800000,0.733333,0.533333,0.450000
16,1,28,1,1,0.625000,0.15,0.290000,0.150000,0.450000,0.200000,0.300000,0.350000
17,1,21,1,1,0.642857,0.40,0.300000,0.100000,0.200000,0.500000,0.400000,0.300000
18,1,21,2,1,0.857143,0.55,0.250000,0.050000,0.300000,0.300000,0.250000,0.350000
19,1,19,1,1,0.214286,0.20,0.613333,0.600000,1.000000,0.333333,0.400000,0.733333
20,1,20,1,1,0.464286,0.10,0.550000,0.500000,1.000000,0.733333,0.450000,0.450000
21,1,23,2,1,0.375000,0.60,0.430000,0.150000,0.350000,0.600000,0.550000,0.500000
22,1,21,1,4,0.428571,0.25,0.580000,0.500000,0.650000,0.450000,0.600000,0.700000
23,1,18,1,1,0.321429,0.20,0.770000,0.850000,0.800000,0.850000,0.600000,0.750000
24,1,18,1,1,0.214286,0.20,0.680000,0.600000,0.800000,0.700000,0.600000,0.700000
26,1,19,2,4,0.625000,1.00,0.500000,0.450000,0.550000,0.700000,0.400000,0.400000
27,1,20,1,1,0.339286,0.20,0.626667,0.450000,0.933333,0.733333,0.533333,0.500000
29,1,21,1,1,0.250000,0.20,0.580000,0.550000,0.700000,0.700000,0.500000,0.450000
34,0,19,2,4,0.500000,0.00,0.490000,0.450000,0.550000,0.450000,0.500000,0.500000
35,0,20,1,1,0.696429,0.70,0.280000,0.350000,0.200000,0.100000,0.350000,0.400000
36,0,18,2,2,0.535714,0.90,0.440000,0.300000,0.550000,0.600000,0.450000,0.300000
37,0,21,2,1,0.660714,0.30,0.330000,0.150000,0.450000,0.600000,0.200000,0.250000
38,0,20,2,1,0.500000,0.05,0.610000,0.650000,0.500000,0.650000,0.700000,0.550000
39,0,20,4,6,0.571429,0.30,0.480000,0.400000,0.550000,0.450000,0.400000,0.600000
40,0,19,1,4,0.250000,0.25,0.620000,0.600000,0.800000,0.650000,0.350000,0.700000
41,0,18,2,4,0.607143,0.40,0.410000,0.250000,0.350000,0.500000,0.600000,0.350000
42,0,20,2,6,0.642857,0.95,0.460000,0.450000,0.600000,0.450000,0.450000,0.350000
43,0,21,2,1,0.392857,0.00,0.660000,0.700000,0.700000,0.600000,0.600000,0.700000
44,0,18,2,4,0.642857,0.55,0.330000,0.250000,0.350000,0.450000,0.350000,0.250000
45,0,18,2,1,0.392857,0.65,0.460000,0.350000,0.700000,0.700000,0.400000,0.150000
46,0,18,2,4,0.625000,0.60,0.300000,0.200000,0.200000,0.200000,0.450000,0.450000
47,0,20,1,1,0.357143,0.50,0.510000,0.350000,0.550000,0.700000,0.500000,0.450000
48,0,18,1,4,0.714286,0.80,0.473684,0.400000,0.533333,0.350000,0.550000,0.550000
49,0,19,2,2,0.750000,0.95,0.380000,0.400000,0.300000,0.600000,0.400000,0.200000
50,0,19,2,4,0.446429,0.50,0.320000,0.300000,0.300000,0.400000,0.300000,0.300000
53,0,18,2,4,0.571429,0.00,0.360000,0.250000,0.300000,0.400000,0.400000,0.450000
54,0,21,2,1,0.285714,0.20,0.680000,0.600000,0.800000,0.750000,0.650000,0.600000
55,0,19,1,4,0.625000,0.70,0.550000,0.550000,0.550000,0.600000,0.550000,0.500000

In [6]:
# rename two columns; AGE to age and IS_PILOT to Pilot

data = data.rename(columns = {"AGE ": "Age", "IS_PILOT": "Pilot"})

In [7]:
# relabel 1 as male and 2 as female

data.loc[data["Gender"] == 1, "Gender"] = "male"
data.loc[data["Gender"] == 2, "Gender"] = "female"

In [8]:
# relabel 1 as yes and 0 as no

data.loc[data["Pilot"] == 1, "Pilot"] = "yes"
data.loc[data["Pilot"] == 0, "Pilot"] = "no"

In [9]:
# filter out rows where Gender is not either male or female and Pilot is not yes or no

data = data.loc[data["Gender"].isin(["male", "female"])]
data = data.loc[data["Pilot"].isin(["yes", "no"])]

In [10]:
# reset index to start from 1

data = data.reset_index(drop = True)
data.index += 1

In [11]:
# filter out race
# only interested in age demographic information for reducing bias

final_data = data[["Pilot", "Age", "Gender", "PSS", "JSS", "MFI", "GF", "PF", "RA", "RM", "MF"]]
final_data

,Pilot,Age,Gender,PSS,JSS,MFI,GF,PF,RA,RM,MF
1,yes,21,male,0.464286,0.40,0.530000,0.650000,0.750000,0.650000,0.500000,0.100000
2,yes,19,female,0.410714,0.50,0.568421,0.500000,0.933333,0.800000,0.450000,0.250000
3,yes,21,male,0.357143,0.25,0.540000,0.550000,0.350000,0.600000,0.400000,0.800000
4,yes,19,male,0.160714,0.00,0.500000,0.550000,0.450000,0.450000,0.500000,0.550000
5,yes,18,female,0.392857,0.30,0.420000,0.300000,0.400000,0.600000,0.500000,0.300000
6,yes,20,male,0.428571,0.30,0.590000,0.600000,0.700000,0.500000,0.600000,0.550000
7,yes,19,female,0.375000,0.30,0.547368,0.533333,0.500000,0.650000,0.500000,0.550000
8,yes,18,female,0.464286,0.50,0.550000,0.550000,0.700000,0.550000,0.550000,0.400000
9,yes,20,female,0.321429,0.20,0.570000,0.500000,0.550000,0.550000,0.600000,0.650000
10,yes,18,male,0.285714,0.00,0.530000,0.750000,0.650000,0.350000,0.450000,0.450000
11,yes,20,male,0.446429,0.55,0.350000,0.250000,0.450000,0.550000,0.350000,0.150000
12,yes,18,male,0.392857,0.15,0.460000,0.450000,0.200000,0.600000,0.550000,0.500000
13,yes,19,female,0.482143,0.40,0.320000,0.250000,0.450000,0.200000,0.250000,0.450000
14,yes,26,male,0.250000,0.20,0.670000,0.650000,0.700000,0.700000,0.650000,0.650000
15,yes,19,male,0.464286,0.40,0.570000,0.550000,0.650000,0.700000,0.650000,0.300000
16,yes,18,male,0.339286,0.30,0.588235,0.500000,0.800000,0.733333,0.533333,0.450000
17,yes,28,male,0.625000,0.15,0.290000,0.150000,0.450000,0.200000,0.300000,0.350000
18,yes,21,male,0.642857,0.40,0.300000,0.100000,0.200000,0.500000,0.400000,0.300000
19,yes,21,female,0.857143,0.55,0.250000,0.050000,0.300000,0.300000,0.250000,0.350000
20,yes,19,male,0.214286,0.20,0.613333,0.600000,1.000000,0.333333,0.400000,0.733333
21,yes,20,male,0.464286,0.10,0.550000,0.500000,1.000000,0.733333,0.450000,0.450000
22,yes,23,female,0.375000,0.60,0.430000,0.150000,0.350000,0.600000,0.550000,0.500000
23,yes,21,male,0.428571,0.25,0.580000,0.500000,0.650000,0.450000,0.600000,0.700000
24,yes,18,male,0.321429,0.20,0.770000,0.850000,0.800000,0.850000,0.600000,0.750000
25,yes,18,male,0.214286,0.20,0.680000,0.600000,0.800000,0.700000,0.600000,0.700000
26,yes,19,female,0.625000,1.00,0.500000,0.450000,0.550000,0.700000,0.400000,0.400000
27,yes,20,male,0.339286,0.20,0.626667,0.450000,0.933333,0.733333,0.533333,0.500000
28,yes,21,male,0.250000,0.20,0.580000,0.550000,0.700000,0.700000,0.500000,0.450000
29,no,19,female,0.500000,0.00,0.490000,0.450000,0.550000,0.450000,0.500000,0.500000
30,no,20,male,0.696429,0.70,0.280000,0.350000,0.200000,0.100000,0.350000,0.400000
31,no,18,female,0.535714,0.90,0.440000,0.300000,0.550000,0.600000,0.450000,0.300000
32,no,21,female,0.660714,0.30,0.330000,0.150000,0.450000,0.600000,0.200000,0.250000
33,no,20,female,0.500000,0.05,0.610000,0.650000,0.500000,0.650000,0.700000,0.550000
34,no,19,male,0.250000,0.25,0.620000,0.600000,0.800000,0.650000,0.350000,0.700000
35,no,18,female,0.607143,0.40,0.410000,0.250000,0.350000,0.500000,0.600000,0.350000
36,no,20,female,0.642857,0.95,0.460000,0.450000,0.600000,0.450000,0.450000,0.350000
37,no,21,female,0.392857,0.00,0.660000,0.700000,0.700000,0.600000,0.600000,0.700000
38,no,18,female,0.642857,0.55,0.330000,0.250000,0.350000,0.450000,0.350000,0.250000
39,no,18,female,0.392857,0.65,0.460000,0.350000,0.700000,0.700000,0.400000,0.150000
40,no,18,female,0.625000,0.60,0.300000,0.200000,0.200000,0.200000,0.450000,0.450000
41,no,20,male,0.357143,0.50,0.510000,0.350000,0.550000,0.700000,0.500000,0.450000
42,no,18,male,0.714286,0.80,0.473684,0.400000,0.533333,0.350000,0.550000,0.550000
43,no,19,female,0.750000,0.95,0.380000,0.400000,0.300000,0.600000,0.400000,0.200000
44,no,19,female,0.446429,0.50,0.320000,0.300000,0.300000,0.400000,0.300000,0.300000
45,no,18,female,0.571429,0.00,0.360000,0.250000,0.300000,0.400000,0.400000,0.450000
46,no,21,female,0.285714,0.20,0.680000,0.600000,0.800000,0.750000,0.650000,0.600000
47,no,19,male,0.625000,0.70,0.550000,0.550000,0.550000,0.600000,0.550000,0.500000

In [12]:
final_data.to_csv("preprocessed_pilot_non-pilot_data.csv", index = False)